disabled_rules:
  - function_body_length
  - identifier_name
  - type_body_length
  - line_length
  - trailing_whitespace
  - valid_ibinspectable
  - switch_case_alignment
#included:
#  - CashDoc/Sources
excluded:
  - Carthage
  - Pods
  - Cashdoc/Libraries
  - CashdocTests
  - CashdocUITests
  - vendor
file_length:
  warning: 1000
  error: 1500
cyclomatic_complexity:
  warning: 50
  error: 100
